name = "cf-news-telegram-bot"
main = "index.js"
compatibility_date = "2024-05-18"
node_compat = true

# KV Namespace එක නිර්වචනය කිරීම
# මෙම නම Cloudflare Dashboard එකේ දිස්වනු ඇත.
kv_namespaces = [
  { binding = "NEWS_STATE", id = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" } # 🚨 ඔබ Worker එක Deploy කළ පසු මෙම ID එක ස්වයංක්‍රීයව සකසනු ඇත.
]

# 🚨 Cron Trigger (Scheduled Event)
# මෙය මඟින් while(true) loop එක ප්‍රතිස්ථාපනය වේ.
# "*/10 * * * *" යන්නෙන් සෑම විනාඩි 10කට වරක් Bot එක ක්‍රියාත්මක වේ.
[triggers]
crons = ["*/1 * * * *"] 

[secrets]
# Bot Token එක රහස්‍ය විචල්‍යයක් (Secret) ලෙස තැබීම අනිවාර්යයි
 BOT_TOKEN = "8299929776:AAGKU7rkfakmDBXdgiGSWzAHPgLRJs-twZg" 
# CHAT_ID එකද රහස්‍ය විචල්‍යයක් ලෙස තැබීම ආරක්ෂිතයි
 CHAT_ID = "-1003177936060"
