# =================================================================
# [BASE CONFIGURATION] - පොදු ව්‍යාපෘති සැකසුම (Root Level)
# =================================================================
# Root level එකේ නමක් අවශ්‍ය නැත, නමුත් compatibility flags/dates පොදුවේ යෙදිය හැකියි.
compatibility_date = "2025-10-12"
compatibility_flags = ["nodejs_compat"]


# KV Namespace එක නිර්වචනය කිරීම (දෙදෙනාටම එකම එකක් අවශ්‍යයි)
# මෙය root level එකේ තැබිය හැක, නැතහොත් workers වගන්ති තුළටම දැමිය හැක.
# =================================================================
# [[WORKER 1: FUNDAMENTAL NEWS (index.js)]]
# =================================================================
[[workers]]
name = "cfnews2000-fundamental" 
main = "index.js"             # Fundamental News කේත ගොනුව

# Fundamental Worker හි Triggers (workers.triggers sub-table)
[workers.triggers]
crons = ["*/10 * * * *"] # සෑම විනාඩි 10කට වරක්


# =================================================================
# [[WORKER 2: ECONOMIC NEWS (economic.js)]]
# =================================================================
[[workers]]
name = "cfnews2000-economic" 
main = "economic.js"          # Economic News කේත ගොනුව

# Economic Worker හි Triggers (workers.triggers sub-table)
[workers.triggers]
crons = ["*/5 * * * *"] # උදා: සෑම විනාඩි 5කට වරක් (ඔබගේ අවශ්‍යතාව අනුව වෙනස් කරන්න)
