name = "cfnewsbot2005" # 🚨 නම Worker CI/CD එකේ නමට ගැලපෙන පරිදි යාවත්කාලීන කරන ලදී.
main = "index.js"
compatibility_date = "2024-05-18"

# ❌node_compat = true වෙනුවට මෙය ආදේශ කරන්න.
# 🛠️ නිරාකරණය: Telegraf හි 'fs/promises' දෝෂය මඟහරවා සියලු Node.js APIs සක්‍රීය කරයි.
nodejs_compat = true 

# KV Namespace එක නිර්වචනය කිරීම
# ඔබගේ ID එක මෙහිදී XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX වෙනුවට තබන්න.
kv_namespaces = [
  { binding = "NEWS_STATE", id = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" }
]

# Cron Trigger (Scheduled Event)
[triggers]
# '*/1 * * * *' යනු සෑම විනාඩියකටම වරක්.
crons = ["*/1 * * * *"] 

# 🚨 සටහන: [secrets] කොටස මෙම ගොනුවෙන් සම්පූර්ණයෙන්ම ඉවත් කර ඇත.
