name = "cfnewsbot2005"
main = "index.js"
compatibility_date = "2024-05-18"

# 🛠️ නිවැරදි කිරීම: nodejs_compat, compatibility_flags array එකක් ලෙස යොදන්න.
compatibility_flags = ["nodejs_compat"]

# KV Namespace එක නිර්වචනය කිරීම
kv_namespaces = [
  { binding = "NEWS_STATE", id = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" }
]

# Cron Trigger (Scheduled Event)
[triggers]
crons = ["*/1 * * * *"] 
